---
- hosts: local
  gather_facts: false
  become: true
  roles:
    - packages
    - zsh
    - gh
    - wireguard
    - kitty
    - hyprland
    - caelestia
    - 1password
    - keyd
    - iris
    - logind
    - capture
    - sddm
    - pipewire
