---
- name: Install keyd
  become: true
  community.general.pacman:
    name: keyd
    state: present

- name: Deploy keyd config
  become: true
  copy:
    src: default.conf
    dest: /etc/keyd/default.conf
  notify: restart keyd

- name: Deploy keyd config for Logitech MX Keys Mini
  become: true
  copy:
    src: logitech-mxkeys.conf
    dest: /etc/keyd/logitech-mxkeys.conf
  notify: restart keyd

- name: Enable and start keyd
  become: true
  systemd:
    name: keyd
    enabled: true
    state: started
