background {
    monitor =
    color = rgba(17, 17, 17, 1.0)
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.3
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(30, 30, 30, 1.0)
    font_color = rgba(220, 220, 220, 1.0)
    fade_on_empty = false
    placeholder_text = <i>Password...</i>
    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    font_size = 64
    font_family = JetBrains Mono Nerd Font
    color = rgba(220, 220, 220, 1.0)
    position = 0, 120
    halign = center
    valign = center
}
