---
- name: Create waybar config dir
  become: false
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/waybar"
    state: directory

- name: Deploy waybar config
  become: false
  copy:
    src: config
    dest: "{{ lookup('env', 'HOME') }}/.config/waybar/config"
    backup: yes

- name: Deploy waybar style
  become: false
  copy:
    src: style.css
    dest: "{{ lookup('env', 'HOME') }}/.config/waybar/style.css"
    backup: yes

- name: Create local bin dir
  become: false
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/bin"
    state: directory

- name: Deploy bt-airpods helper script
  become: false
  copy:
    src: bt-airpods
    dest: "{{ lookup('env', 'HOME') }}/.local/bin/bt-airpods"
    mode: "0755"
